version: '3.6'

services:
  postgres:
    container_name: postgres
    image: postgres:10.5
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file: .env
    volumes:
      - $DATA_ROOT/postgres:/var/lib/postgresql/data

